### PR TITLE
Miopen bwd conv fixes

### PR DESCRIPTION
**Pull request by ashishfarmer**

### CODE REVIEW

**Comment by ashishfarmer** [comment]
@petrex The high level tests seem to be working with these fixes. The PR is ready for review

**Review by petrex — CHANGES_REQUESTED** [review]
@ashishfarmer thanks! Can you check why CI is failing?

**Comment by ashishfarmer** [comment]
@petrex Looks like clang-format issue. Let me fix the formatting

**Review by petrex — APPROVED** [review]
looks good

**Pull request merged**
