### PR TITLE
changed the docker image

### PR DESCRIPTION
**Pull request by rohithkrn**
changed the docker image to test inference test

### CODE REVIEW

**Review by petrex — CHANGES_REQUESTED** [review]
@rohithkrn please check-in the dockerfile and build the image in the Jenkins pipeline.

**Comment by rohithkrn** [comment]
I will do it eventually. I wanted check if the image is working first.

**Comment by petrex** [comment]
@rohithkrn  pls verify the CI related change on `jenkins` branch.

**Comment by rohithkrn** [comment]
Ok.

**Pull request closed without merging**
