### PR TITLE
udated inference_test path

### PR DESCRIPTION
**Pull request by rohithkrn**

### CODE REVIEW

**Comment by petrex** [comment]
@rohithkrn I saw build failing on CI. Can you look into that thanks!

**Comment by rohithkrn** [comment]
Yes. Working on that.

**Comment by rohithkrn** [comment]
Removed inference test in the jenkins pipeline for now due to "permission denied" errors. All others stages in pipeline are passing. Will add inference test once we have the dockerfile.

**Review by petrex — APPROVED** [review]
pls enable "python ops tests" and "inference test" in the next sprint

**Pull request merged**
